<?php

use App\Game;
use Faker\Generator as Faker;

$factory->define(App\Clip::class, function (Faker $faker) {

	$clips = [
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=ip7OYzQ40oQ'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=SuoJTLiAGHQ'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=COZAyzD3SRU'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=O1JRCpn1Cpc'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=GuOxbVYOLUI'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=oOC7vtkxddw'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=cp5UGTFRZVo'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=I76NFYRgGV4'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=RtCBXf3Jbms'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=zVk9EIKmsQc'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=5o_yUPcDNN8'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=2__YcIoHkcg'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=iL0y02Z9RUU'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=6wPPEqAWA48'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=UvkupeCszSc'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=ujsXkUNfIy0'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=s2zEjUHMLN8'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=hy9_8iPtLG4'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=-y_K-qY1oHU'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=aG0mcz8-BLM'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=JWhxCWvtZPU'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=u96r8uwW8Do'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=cXFJgKA7Gw8'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=lwOL3bzoPdo'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=tenPyeEmvfo'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=tgg3ErtGbyM'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=50yBl5rhaNg'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=2eoTt-5qsWE'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=A8eVzSFZjag'],
		['game_id' => 1, 'url' => 'https://www.youtube.com/watch?v=U2MYkclb0vc'],

		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=GU4X_23ZmVM'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=mW5dqf6l20E'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=OSptvCQMsR0'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=r9WG5Jop6jo'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=Y6DcKEKJ8Es'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=pf0js_cckOc'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=h-hs6-tA9qQ'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=ljoSbOMppdU'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=esRhsH0EJKc'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=aogu-rSJQvk'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=IBiLAxDkCaU'],
		['game_id' => 3, 'url' => 'https://www.youtube.com/watch?v=zXlvBWcNmaQ'],

		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=JX8dHPpTXJM'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=zW3mQU0FSsA'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=fuit0s0qQb4'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=FHRPX-JdmgI'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=_7g-ga70jCo'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=Cj7cOvklxEY'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=D0g7CudcIA8'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=BSspHvrl0YA'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=UoRSaFmC85c'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=FU0yaqIer54'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=bJe0f4Ko7nE'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=2gW54RyLmcw'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=eHRc23bF3uE'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=kttOotNjvog'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=60JDM_QLj-0'],
		['game_id' => 2, 'url' => 'https://www.youtube.com/watch?v=ymL04LzzPpA'],

		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=cmmXBUTCE60'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=_lQ_-77DqvQ'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=uGqEshcgYyQ'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=z4Ono6ixDzU'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=3YQqrsz_-uI'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=0HdLA31XiYM'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=HXkxJxLnIGM'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=fFYj8-9H28k'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=gcpe4J3O_tE'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=-il9lp2CsqY'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=N85SIotSZCs'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=uOfpPVDftRg'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=mQ7uE6LON60'],
		['game_id' => 4, 'url' => 'https://www.youtube.com/watch?v=ljLihOJCtys'],

		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=__rhB5u3Ez0'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=24ITl_Y2t1E'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=TzpG7YjNohE'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=11hYDK1_yi0'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=mk-9gLP5LCM'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=SZFceas3vg4'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=m-TagSsh9Ac'],
		['game_id' => 5, 'url' => 'https://www.youtube.com/watch?v=T3T8f2ftXFU'],

		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=zkUm_xbEnCg'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=zx964U2yZcA'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=DcXnuo_CVS8'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=MydjKXR8kdk'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=Y6KumJWXIT0'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=RK8vl7mfSMQ'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=YvDTB0cLlX4'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=0iDUXtiOU-4'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=u8-y78G3IcA'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=kB2Q1bdRQrA'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=dLMZXNJxHQ8'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=FeBEvwb5f9k'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=tzkccwQK9zc'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=wnvZ6oVRH2U'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=w9Iz3tlxIco'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=ddzJJK6BHT8'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=1O05oB8zmpY'],
		['game_id' => 12, 'url' => 'https://www.youtube.com/watch?v=ECyeqgnqQYk'],
	];

	$clip = $clips[rand(0, count($clips))];

    return [
        'game_id' => $clip['game_id'],
        'title' => $faker->text($maxNbChars = 64),
        'url' => $clip['url'],
        'start_time' => 0,
        'end_time' => 0,
        'views' => $faker->numberBetween($min = 1000, $max = 90000),
        'rating' => $faker->numberBetween($min = 500, $max = 3000),
    ];
});
